#!/usr/bin/env npx tsx
/**
 * Verify selected_trips canary readiness with staging token + flags (process-local).
 * Does not mutate a remote deploy — prints export hints for the staging host.
 *
 *   npm run lab:enable-selected-trips-canary
 *   npm run lab:enable-selected-trips-canary -- --apply-local-check
 */

import { existsSync, readFileSync, writeFileSync } from 'fs';
import { join } from 'path';
import { PLANNING_SIGNOFF_ROOT } from './load-planning-signoff';
import { evaluateOrtToolsAuthorityCanaryGate } from '../ortools-authority-canary.gate';
import { resolveAuthoritativeRepairProviderForRequest } from '../ortools-authority-canary.gate';
import { loadApprovedAuthorityPackage } from './selected-trips-canary';
import { loadSelectedTripsWhitelist } from './selected-trips-canary';

function loadEnvFile(path: string): void {
  if (!existsSync(path)) return;
  for (const line of readFileSync(path, 'utf8').split('\n')) {
    const t = line.trim();
    if (!t || t.startsWith('#')) continue;
    const i = t.indexOf('=');
    if (i < 0) continue;
    process.env[t.slice(0, i)] = t.slice(i + 1);
  }
}

async function main(): Promise<number> {
  const tokenEnv = join(PLANNING_SIGNOFF_ROOT, '.staging-authority-token.env');
  if (!existsSync(tokenEnv)) {
    console.error('FAIL: missing .staging-authority-token.env — mint first');
    return 1;
  }
  loadEnvFile(tokenEnv);

  const enablePath = join(PLANNING_SIGNOFF_ROOT, '.staging-canary-enable.env');
  const body = [
    '# Generated by lab:enable-selected-trips-canary — staging host only',
    '# Kill: unset OR_TOOLS_AUTHORITATIVE_CANARY; OR_TOOLS_CANARY_STAGE=shadow',
    `OR_TOOLS_AUTHORITY_TOKEN_SECRET=${process.env.OR_TOOLS_AUTHORITY_TOKEN_SECRET ?? ''}`,
    `OR_TOOLS_AUTHORITY_TOKEN=${process.env.OR_TOOLS_AUTHORITY_TOKEN ?? ''}`,
    'OR_TOOLS_AUTHORITY_ENVIRONMENT=staging',
    'OR_TOOLS_CANARY_STAGE=selected_trips',
    'OR_TOOLS_AUTHORITATIVE_CANARY=1',
    '',
  ].join('\n');
  writeFileSync(enablePath, body, 'utf8');

  const applyLocal = process.argv.includes('--apply-local-check');
  if (applyLocal) {
    process.env.OR_TOOLS_AUTHORITY_ENVIRONMENT = 'staging';
    process.env.OR_TOOLS_CANARY_STAGE = 'selected_trips';
    process.env.OR_TOOLS_AUTHORITATIVE_CANARY = '1';
  }

  const pkg = loadApprovedAuthorityPackage();
  const wl = loadSelectedTripsWhitelist();
  const tripId = wl?.tripIds?.[0] ?? 'ra01_is_01';
  const gate = evaluateOrtToolsAuthorityCanaryGate({
    writeAttemptedTotal: 0,
    realGoldActiveCount: 5,
    stabilitySignedOff: true,
    localitySignedOff: true,
    gatewaySignedOff: true,
    rollbackReady: true,
    ignoreSignoffBundle: true,
    authorityPackageOverride: pkg,
  });
  const provider = resolveAuthoritativeRepairProviderForRequest({
    tripId,
    operation: 'REROUTE',
    gate,
    pkg: pkg ?? undefined,
  });

  console.log(
    JSON.stringify(
      {
        enableEnvFile: enablePath.replace(`${process.cwd()}/`, ''),
        localCheck: applyLocal,
        gate: {
          mode: gate.mode,
          releaseAuthorized: gate.releaseAuthorized,
          authoritativePromotion: gate.authoritativePromotion,
          canaryStage: gate.canaryStage,
        },
        sample: { tripId, provider },
        hostApply: [
          `set -a; source ${enablePath.replace(`${process.cwd()}/`, '')}; set +a`,
          'restart / reload staging API so Decision Runtime picks up env',
          'curl .../ortools-shadow/authority/gate | jq',
          'Kill-switch: see solver/CANARY_ROLLBACK_SOP.md',
        ],
        note: applyLocal
          ? 'Process-local canary ON for this check only'
          : 'Flags NOT applied to this process — file written for staging host',
      },
      null,
      2,
    ),
  );

  if (applyLocal && (!gate.releaseAuthorized || provider !== 'ortools-repair')) {
    return 1;
  }
  return 0;
}

main()
  .then((c) => process.exit(c))
  .catch((e) => {
    console.error(e);
    process.exit(1);
  });
