/**
 * M4-RA-01 Rollback Drill — checklist + optional offline simulation.
 *
 *   npm run lab:rollback-drill -- --checklist
 */

import { resolveCanaryStage } from './selected-trips-canary';
import { evaluateOrtToolsAuthorityCanaryGate } from '../ortools-authority-canary.gate';

const CHECKLIST = [
  {
    id: 'RD-01',
    item: 'selected trip temporarily uses ortools-repair under canary',
  },
  {
    id: 'RD-02',
    item: 'Inject fault or breach metric (e.g. mark evidence stale / force fallback)',
  },
  {
    id: 'RD-03',
    item: 'Unset OR_TOOLS_AUTHORITATIVE_CANARY (and/or stage→shadow)',
  },
  {
    id: 'RD-04',
    item: 'authoritativeRepairProviderId resolves to neptune-repair',
  },
  {
    id: 'RD-05',
    item: 'In-flight authorized-but-not-executed ortools candidates discarded',
  },
  {
    id: 'RD-06',
    item: 'Stale-evidence OR-Tools attachments invalidated (no continue-execute)',
  },
  {
    id: 'RD-07',
    item: 'Same problem regenerated by Neptune — not reused from old ortools candidate',
  },
  {
    id: 'RD-08',
    item: 'No duplicate Plan Version writes',
  },
  {
    id: 'RD-09',
    item: 'User does not see duplicate decision cards',
  },
  {
    id: 'RD-10',
    item: 'Seal drill evidence under planning-signoff/<date>/rollback-drill.json',
  },
];

async function main(): Promise<number> {
  const report = evaluateOrtToolsAuthorityCanaryGate();
  const stage = resolveCanaryStage();

  if (process.argv.includes('--simulate-off')) {
    const prev = process.env.OR_TOOLS_AUTHORITATIVE_CANARY;
    delete process.env.OR_TOOLS_AUTHORITATIVE_CANARY;
    process.env.OR_TOOLS_CANARY_STAGE = 'shadow';
    const after = evaluateOrtToolsAuthorityCanaryGate({
      writeAttemptedTotal: 0,
      ignoreSignoffBundle: false,
    });
    console.log(
      JSON.stringify(
        {
          simulation: 'canary_off',
          beforeStage: stage,
          afterMode: after.mode,
          afterAuthoritativePromotion: after.authoritativePromotion,
          providerMustBe: 'neptune-repair',
          note: 'Env mutated only inside this process — restore deploy config after drill',
        },
        null,
        2,
      ),
    );
    if (prev !== undefined) process.env.OR_TOOLS_AUTHORITATIVE_CANARY = prev;
    return after.authoritativePromotion ? 1 : 0;
  }

  console.log('M4-RA-01 Rollback Drill Checklist');
  console.log('=================================');
  console.log(`Current mode:  ${report.mode}`);
  console.log(`Stage:         ${stage}`);
  console.log(`Engineering:   ${report.engineeringReady ? 'READY' : 'NOT READY'}`);
  console.log(`Release:       ${report.releaseAuthorized ? 'AUTHORIZED' : 'BLOCKED'}`);
  console.log('');
  for (const row of CHECKLIST) {
    console.log(`[ ] ${row.id}  ${row.item}`);
  }
  console.log('');
  console.log('Pass criteria: all items checked in a live selected_trips environment.');
  console.log('Offline smoke: npm run lab:rollback-drill -- --simulate-off');
  console.log('');
  console.log(
    JSON.stringify(
      {
        schemaId: 'tripnara.ortools_rollback_drill_checklist@v1',
        items: CHECKLIST,
        rollbackHint: report.rollbackHint,
      },
      null,
      2,
    ),
  );
  return 0;
}

main()
  .then((c) => process.exit(c))
  .catch((e) => {
    console.error(e);
    process.exit(1);
  });
