/**
 * P0 Semantic Keys — NARA_LOOK_P0_V1
 * evidence/work-packages/NARA-LOOK-P0/s0-contracts/SemanticKeys.md
 */

export const NARA_LOOK_SEMANTIC_KEYS_VERSION = 'NARA_LOOK_P0_V1_2' as const;

export const NARA_LOOK_SEMANTIC_KEYS = [
  'OBSERVATION.VEHICLE.CLASS_DETECTED',
  'OBSERVATION.VEHICLE.DRIVETRAIN_DETECTED',
  'OBSERVATION.VEHICLE.MODEL_DETECTED',
  'DATA_UNCERTAINTY.VEHICLE_DRIVETRAIN_UNKNOWN',
  'RULE_TRIGGER.FROAD_VEHICLE_MISMATCH',
  'OBSERVATION.ROAD.FROAD_SIGN_DETECTED',
  'OBSERVATION.ROAD.CLOSED_SIGN_DETECTED',
  'OBSERVATION.ROAD.GRAVEL_SURFACE_DETECTED',
  'OBSERVATION.ROAD.WATER_CROSSING_DETECTED',
  'DATA_UNCERTAINTY.ROAD_ID_UNKNOWN',
  'DATA_CONFLICT.ROAD_STATUS_CONFLICT',
  'OBSERVATION.ACTIVITY.OPERATOR_SIGN_DETECTED',
  'OBSERVATION.ACTIVITY.ENTRY_DETECTED',
  'EXECUTION_DEVIATION.WRONG_MEETING_POINT',
  'EXECUTION_DEVIATION.MEETING_POINT_DISTANCE',
  'RISK.ACTIVITY_LATE_ARRIVAL',
  'OBSERVATION.PARKING.SIGN_DETECTED',
  'OBSERVATION.PARKING.NO_PARKING_DETECTED',
  'OBSERVATION.PARKING.PAID_ZONE_DETECTED',
  'OBSERVATION.PARKING.TIME_LIMIT_DETECTED',
  'OBSERVATION.PARKING.RESIDENT_ONLY_DETECTED',
  'DATA_UNCERTAINTY.PARKING_RULE_INCOMPLETE',
  'RULE_TRIGGER.PARKING_NOT_ALLOWED_NOW',
  'OBSERVATION.RENTAL.HANDOVER_TYPE',
  'OBSERVATION.RENTAL.DAMAGE_SUSPECTED',
  'OBSERVATION.RENTAL.MILEAGE_DETECTED',
  'OBSERVATION.RENTAL.FUEL_LEVEL_DETECTED',
  'OBSERVATION.RENTAL.PLATE_DETECTED',
  'DATA_UNCERTAINTY.RENTAL_VIEWS_INCOMPLETE',
  'DATA_UNCERTAINTY.GPS_INSUFFICIENT',
  'DATA_UNCERTAINTY.CONTEXT_MISSING',
  'DATA_CONFLICT.IMAGE_LOCATION_MISMATCH',
  'DATA_UNCERTAINTY.OFFICIAL_DATA_UNAVAILABLE',
] as const;

export type NaraLookSemanticKey = (typeof NARA_LOOK_SEMANTIC_KEYS)[number];

const KEY_SET = new Set<string>(NARA_LOOK_SEMANTIC_KEYS);

export function isFrozenSemanticKey(key: string): key is NaraLookSemanticKey {
  return KEY_SET.has(key);
}
