
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    // NOTE: `prisma generate` doesn't need a live database connection, but
    // Prisma config `env()` enforces presence at install-time (CI often has no DATABASE_URL).
    // Fall back to a dummy localhost URL so type generation can run.
    url: process.env.DATABASE_URL ?? "postgresql://user:pass@localhost:5432/db?schema=public",
  },
});
