/**
 * PLAN_GEN 节点错误语义 SSOT（空草案 / 无解 / 输入不足 / 研究缺失 / 系统失败）。
 * 文档：PLAN_GEN_NODE_PROTOCOL.md
 */

export const PLAN_GEN_NODE_PROTOCOL_VERSION = '1.0.0' as const;

export const PLAN_GEN_ERROR_CODES = {
  PLAN_GEN_EMPTY_DRAFT: 'PLAN_GEN_EMPTY_DRAFT',
  EMPTY_DAYS_FROM_SKILL: 'EMPTY_DAYS_FROM_SKILL',
  INCONSISTENT_EMPTY_DRAFT: 'INCONSISTENT_EMPTY_DRAFT',
  TERMINAL_NO_SOLUTION: 'TERMINAL_NO_SOLUTION',
  NO_TRIP_PLAN_REQUEST: 'NO_TRIP_PLAN_REQUEST',
  MISSING_RESEARCH: 'MISSING_RESEARCH',
  NO_SKILLS_REGISTRY: 'NO_SKILLS_REGISTRY',
  SKILL_NOT_REGISTERED: 'SKILL_NOT_REGISTERED',
  SKILL_RESULT_INVALID: 'SKILL_RESULT_INVALID',
  SKILL_EXECUTION_ERROR: 'SKILL_EXECUTION_ERROR',
  PLAN_GEN_EXECUTOR_UNAVAILABLE: 'PLAN_GEN_EXECUTOR_UNAVAILABLE',
  PLAN_GEN_HARNESS_BLOCKED: 'PLAN_GEN_HARNESS_BLOCKED',
  GOVERNANCE_REPLANNING_DEFERRED: 'GOVERNANCE_REPLANNING_DEFERRED',
} as const;

export type PlanGenErrorCode = (typeof PLAN_GEN_ERROR_CODES)[keyof typeof PLAN_GEN_ERROR_CODES];

export type PlanGenErrorTerminalKind = 'NEED_MORE_INFO' | 'FAILED';

/** 错误码 → 终端语义（澄清 vs 硬失败） */
export const PLAN_GEN_ERROR_TERMINAL: Record<PlanGenErrorCode, PlanGenErrorTerminalKind> = {
  PLAN_GEN_EMPTY_DRAFT: 'NEED_MORE_INFO',
  EMPTY_DAYS_FROM_SKILL: 'NEED_MORE_INFO',
  INCONSISTENT_EMPTY_DRAFT: 'NEED_MORE_INFO',
  TERMINAL_NO_SOLUTION: 'NEED_MORE_INFO',
  NO_TRIP_PLAN_REQUEST: 'NEED_MORE_INFO',
  MISSING_RESEARCH: 'NEED_MORE_INFO',
  NO_SKILLS_REGISTRY: 'FAILED',
  SKILL_NOT_REGISTERED: 'FAILED',
  SKILL_RESULT_INVALID: 'FAILED',
  SKILL_EXECUTION_ERROR: 'FAILED',
  PLAN_GEN_EXECUTOR_UNAVAILABLE: 'FAILED',
  PLAN_GEN_HARNESS_BLOCKED: 'FAILED',
  GOVERNANCE_REPLANNING_DEFERRED: 'NEED_MORE_INFO',
};

export const PLAN_GEN_ERROR_CODE_SET = new Set<string>(Object.values(PLAN_GEN_ERROR_CODES));

export function isPlanGenErrorCode(code: string | undefined | null): code is PlanGenErrorCode {
  return typeof code === 'string' && PLAN_GEN_ERROR_CODE_SET.has(code);
}

export function resolvePlanGenErrorTerminal(
  code: string | undefined | null,
): PlanGenErrorTerminalKind {
  if (isPlanGenErrorCode(code)) {
    return PLAN_GEN_ERROR_TERMINAL[code];
  }
  // 未知码：保守按可澄清处理，避免静默 FAILED 打爆前端
  return 'NEED_MORE_INFO';
}
