/**
 * Iceland Region Golden Sets — revised after coverage QA review.
 * Place IDs are Catalog references; verify coordinates separately in Catalog.
 */

import type { IcelandRegionPlanningPack } from '../types/iceland-region-planning-pack.types';

export const REYKJAVIK_ARRIVAL_PACK: IcelandRegionPlanningPack = {
  packId: 'reykjavik_arrival',
  wizardRegionIds: ['reykjanes'],
  version: '2026-07-qa1',
  status: 'ACTIVE',
  coverageStatus: 'ATTRACTION_READY',
  regionalGoldenSetReady: true,
  displayName: 'Reykjavík & arrival',
  entities: [
    {
      placeId: 381090,
      label: 'Blue Lagoon',
      entityType: 'ATTRACTION',
      coverageRole: 'PRIMARY',
      typicalVisitMinutes: 120,
      representativenessScore: 0.85,
      seasonalAvailability: ['all'],
    },
    {
      placeId: 381054,
      label: 'Reykjavík visitor centre',
      entityType: 'SERVICE',
      routeRoles: ['REST_STOP'],
      coverageRole: 'SUPPORT',
    },
    {
      placeId: 381042,
      label: 'Reykjavík city base',
      displayName: 'Reykjavík (origin base)',
      entityType: 'TOWN_HUB',
      routeRoles: ['ORIGIN_BASE', 'OVERNIGHT_HUB'],
      coverageRole: 'SUPPORT',
      notes: 'Not a lodging product; day-trip ORIGIN_BASE for Golden Circle etc.',
    },
    {
      placeId: 381192,
      label: 'Bónus downtown',
      entityType: 'SERVICE',
      routeRoles: ['SUPPLY_HUB'],
      coverageRole: 'SUPPORT',
    },
    {
      experienceProductId: 'exp_blue_lagoon_admission',
      label: 'Blue Lagoon / geothermal spa admission',
      entityType: 'EXPERIENCE_PRODUCT',
      meetingPlaceId: 381090,
      regionAnchorPlaceId: 381090,
      bookingRequired: true,
      durationMinutes: 120,
      seasonalAvailability: ['all'],
    },
  ],
  relations: [],
  planningPolicy: {
    minRecommendedDays: 0.5,
    idealRecommendedDays: 1,
    directionHints: ['keflavik_to_reykjavik', 'light_city_or_soak'],
    maxCoreAnchorsPerDay: 1,
  },
  sourceRefs: ['catalog:IS_REYKJANES'],
};

export const GOLDEN_CIRCLE_PACK: IcelandRegionPlanningPack = {
  packId: 'golden_circle',
  wizardRegionIds: ['golden_circle'],
  version: '2026-07-qa1',
  status: 'ACTIVE',
  coverageStatus: 'ATTRACTION_READY',
  regionalGoldenSetReady: true,
  displayName: 'Golden Circle',
  entities: [
    {
      placeId: 381037,
      label: 'Þingvellir',
      entityType: 'ATTRACTION',
      coverageRole: 'PRIMARY',
      routeRoles: ['ENTRY_GATEWAY'],
      typicalVisitMinutes: 75,
      representativenessScore: 1,
      notes: 'coverageRole PRIMARY + routeRole ENTRY_GATEWAY on same entity',
    },
    {
      placeId: 381083,
      label: 'Geysir Geothermal Area',
      displayName: 'Geysir / Haukadalur Geothermal Area (Strokkur)',
      entityType: 'ATTRACTION_AREA',
      coverageRole: 'PRIMARY',
      typicalVisitMinutes: 45,
      representativenessScore: 0.95,
      notes: 'Prefer area name; active geyser is typically Strokkur',
    },
    {
      placeId: 381084,
      label: 'Gullfoss',
      entityType: 'ATTRACTION',
      coverageRole: 'PRIMARY',
      routeRoles: ['EXIT_GATEWAY'],
      typicalVisitMinutes: 40,
      representativenessScore: 0.95,
    },
    {
      placeId: 389399,
      label: 'Kerið crater',
      displayName: 'Kerið',
      entityType: 'ATTRACTION',
      coverageRole: 'SECONDARY',
      typicalVisitMinutes: 45,
      representativenessScore: 0.82,
      notes: 'South of classic loop — often late-day stop toward Selfoss',
    },
    {
      placeId: 388608,
      label: 'Brúarfoss',
      displayName: 'Brúarfoss Waterfall',
      entityType: 'ATTRACTION',
      coverageRole: 'SECONDARY',
      typicalVisitMinutes: 40,
      representativenessScore: 0.78,
      notes: 'Near Geysir/Gullfoss corridor',
    },
    {
      placeId: 388566,
      label: 'Faxafoss',
      displayName: 'Faxafoss (Faxi)',
      entityType: 'ATTRACTION',
      coverageRole: 'SECONDARY',
      typicalVisitMinutes: 25,
      representativenessScore: 0.72,
      notes: 'Between Gullfoss corridor and lower Golden Circle',
    },
    {
      placeId: 389622,
      label: 'Laugarvatn Fontana',
      displayName: 'Laugarvatn Fontana Geothermal Baths',
      entityType: 'ATTRACTION',
      coverageRole: 'SECONDARY',
      typicalVisitMinutes: 75,
      representativenessScore: 0.8,
      notes: 'Between Þingvellir and Geysir — soak / geothermal stop',
    },
    {
      placeId: 381042,
      label: 'Reykjavík origin base',
      entityType: 'TOWN_HUB',
      routeRoles: ['ORIGIN_BASE'],
      coverageRole: 'SUPPORT',
      notes: 'Day-trip base — not regional lodging',
    },
  ],
  relations: [
    {
      groupId: 'gc_classic_loop',
      relationType: 'CO_VISIT_CLUSTER',
      memberPlaceIds: [381037, 381083, 381084],
      notes: 'Classic trio; not forced all-or-nothing by day capacity',
    },
    {
      groupId: 'gc_geyser_corridor',
      relationType: 'CO_VISIT_CLUSTER',
      memberPlaceIds: [381083, 388608, 388566],
      notes: 'Geysir corridor secondaries — soft co-visit when capacity allows',
    },
  ],
  planningPolicy: {
    minRecommendedDays: 1,
    idealRecommendedDays: 2,
    directionHints: [
      'reykjavik_loop_clockwise',
      'thingvellir_fontana_geysir_gullfoss_kerid',
    ],
    maxCoreAnchorsPerDay: 3,
  },
  sourceRefs: ['planning-policy:GOLDEN_CIRCLE_INTENT', 'catalog:IS_GOLDEN_CIRCLE'],
};

export const SOUTH_COAST_WEST_PACK: IcelandRegionPlanningPack = {
  packId: 'south_coast_west',
  wizardRegionIds: ['south_coast'],
  version: '2026-07-qa1',
  status: 'ACTIVE',
  coverageStatus: 'ATTRACTION_READY',
  regionalGoldenSetReady: true,
  displayName: 'South Coast (west)',
  entities: [
    {
      placeId: 381080,
      label: 'Seljalandsfoss',
      entityType: 'ATTRACTION',
      coverageRole: 'PRIMARY',
      routeRoles: ['ENTRY_GATEWAY'],
      typicalVisitMinutes: 60,
      representativenessScore: 1,
    },
    {
      placeId: 381038,
      label: 'Skógafoss',
      entityType: 'ATTRACTION',
      coverageRole: 'PRIMARY',
      typicalVisitMinutes: 60,
      representativenessScore: 0.98,
    },
    {
      placeId: 381039,
      label: 'Reynisfjara',
      entityType: 'ATTRACTION',
      coverageRole: 'PRIMARY',
      typicalVisitMinutes: 75,
      representativenessScore: 0.97,
    },
    {
      placeId: 381082,
      label: 'Dyrhólaey',
      entityType: 'ATTRACTION',
      coverageRole: 'SECONDARY',
      typicalVisitMinutes: 45,
      representativenessScore: 0.8,
    },
    {
      placeId: 381092,
      label: 'Vík í Mýrdal',
      entityType: 'TOWN_HUB',
      coverageRole: 'SUPPORT',
      routeRoles: [
        'REST_STOP',
        'MEAL_HUB',
        'OVERNIGHT_HUB',
        'WEATHER_FALLBACK_HUB',
      ],
      notes: 'Town hub — not scored as attraction PRIMARY',
    },
    {
      placeId: 381045,
      label: 'Vík Hostel',
      entityType: 'LODGING',
      routeRoles: ['OVERNIGHT_HUB'],
      coverageRole: 'SUPPORT',
    },
    {
      placeId: 381081,
      label: 'Sólheimasandur',
      entityType: 'ATTRACTION',
      coverageRole: 'SECONDARY',
      typicalVisitMinutes: 45,
    },
    {
      placeId: 381098,
      label: 'Eyjafjallajökull viewpoint (verify visit point)',
      entityType: 'ATTRACTION',
      coverageRole: 'SECONDARY',
      typicalVisitMinutes: 30,
      notes:
        'Catalog must bind a reachable VISIT_POINT, not glacier centroid. QA pending.',
    },
  ],
  relations: [
    {
      groupId: 'scw_coast',
      relationType: 'SOFT_ALTERNATIVE',
      memberPlaceIds: [381039, 381082],
      notes:
        'Same day OK when time/weather allows; pick one under wind/time pressure — not HARD_EXCLUSIVE',
    },
    {
      groupId: 'scw_waterfalls',
      relationType: 'CO_VISIT_CLUSTER',
      memberPlaceIds: [381080, 381038],
    },
  ],
  planningPolicy: {
    minRecommendedDays: 1,
    idealRecommendedDays: 2,
    directionHints: ['west_to_east_along_ring_road', 'overnight_vik'],
    maxCoreAnchorsPerDay: 3,
    seasonalBufferMinutes: 30,
  },
  sourceRefs: ['catalog:IS_SOUTH_COAST'],
  notes: [
    'Weather fallback should eventually point at indoor Vík nodes (museum/church/shop), not only town hub.',
  ],
};

export const SOUTH_COAST_EAST_PACK: IcelandRegionPlanningPack = {
  packId: 'south_coast_east',
  wizardRegionIds: ['south_coast'],
  version: '2026-07-qa1',
  status: 'ACTIVE',
  coverageStatus: 'ATTRACTION_READY',
  regionalGoldenSetReady: true,
  displayName: 'South Coast east / glacier corridor',
  entities: [
    {
      placeId: 381088,
      label: 'Skaftafell',
      entityType: 'ATTRACTION_AREA',
      coverageRole: 'PRIMARY',
      routeRoles: ['ENTRY_GATEWAY'],
      typicalVisitMinutes: 90,
      representativenessScore: 0.9,
    },
    {
      placeId: 381093,
      label: 'Svartifoss',
      entityType: 'ATTRACTION',
      coverageRole: 'SECONDARY',
      parentPlaceId: 381088,
      typicalVisitMinutes: 60,
      representativenessScore: 0.75,
      notes: 'Child of Skaftafell — do not double-count coverage',
    },
    {
      placeId: 381041,
      label: 'Jökulsárlón',
      entityType: 'ATTRACTION',
      coverageRole: 'PRIMARY',
      typicalVisitMinutes: 75,
      representativenessScore: 1,
    },
    {
      placeId: 381089,
      label: 'Diamond Beach',
      entityType: 'ATTRACTION',
      coverageRole: 'PRIMARY',
      typicalVisitMinutes: 45,
      representativenessScore: 0.92,
    },
    {
      placeId: 381053,
      label: 'Skaftafell Campsite',
      entityType: 'LODGING',
      routeRoles: ['OVERNIGHT_HUB'],
      coverageRole: 'SUPPORT',
    },
    {
      placeId: 381048,
      label: 'Fosshotel Glacier Lagoon',
      entityType: 'LODGING',
      routeRoles: ['OVERNIGHT_HUB'],
      coverageRole: 'SUPPORT',
    },
    {
      placeId: 381047,
      label: 'Höfn',
      entityType: 'TOWN_HUB',
      routeRoles: ['EXIT_GATEWAY', 'OVERNIGHT_HUB'],
      coverageRole: 'SUPPORT',
      notes: 'Town hub / exit toward east — not an attraction PRIMARY',
    },
    {
      placeId: 381055,
      label: 'Skaftafell visitor centre',
      entityType: 'SERVICE',
      routeRoles: ['WEATHER_FALLBACK_HUB', 'REST_STOP'],
      coverageRole: 'SUPPORT',
    },
    {
      placeId: 381075,
      label: 'N1 Höfn',
      entityType: 'SERVICE',
      routeRoles: ['SUPPLY_HUB'],
      coverageRole: 'SUPPORT',
    },
    {
      experienceProductId: 'exp_glacier_hike_skaftafell',
      label: 'Glacier hike / ice cave (bookable)',
      entityType: 'EXPERIENCE_PRODUCT',
      meetingPlaceId: 381088,
      regionAnchorPlaceId: 381088,
      bookingRequired: true,
      durationMinutes: 180,
      seasonalAvailability: ['winter', 'shoulder'],
      notes: 'Never reuse placeId 381088 as the product id',
    },
  ],
  relations: [
    {
      groupId: 'sce_skaftafell_svartifoss',
      relationType: 'PARENT_CHILD',
      memberPlaceIds: [381088, 381093],
      notes: 'Skaftafell AREA → Svartifoss hike activity',
    },
    {
      groupId: 'sce_lagoon',
      relationType: 'CO_VISIT_CLUSTER',
      memberPlaceIds: [381041, 381089],
      notes: 'Usually co-visit; planner decides both/order/shorten — not exclusive',
    },
  ],
  planningPolicy: {
    minRecommendedDays: 1,
    idealRecommendedDays: 2,
    directionHints: ['vik_to_hofn', 'overnight_near_lagoon'],
    maxCoreAnchorsPerDay: 2,
    seasonalBufferMinutes: 45,
  },
  sourceRefs: ['catalog:glacier_corridor'],
};

export const SNAEFELLSNES_PACK: IcelandRegionPlanningPack = {
  packId: 'snaefellsnes',
  wizardRegionIds: ['snaefellsnes'],
  version: '2026-07-qa1',
  status: 'ACTIVE',
  coverageStatus: 'ATTRACTION_READY',
  regionalGoldenSetReady: true,
  displayName: 'Snæfellsnes',
  entities: [
    {
      placeId: 381040,
      label: 'Kirkjufell',
      entityType: 'ATTRACTION',
      coverageRole: 'PRIMARY',
      typicalVisitMinutes: 60,
      representativenessScore: 1,
      notes: 'Prefer pairing with Kirkjufellsfoss visit-point when Catalog has it',
    },
    {
      placeId: 381099,
      label: 'Snæfellsjökull National Park',
      entityType: 'ATTRACTION_AREA',
      coverageRole: 'PRIMARY',
      typicalVisitMinutes: 90,
      representativenessScore: 0.95,
      aliasPlaceIds: [381087],
      notes: 'canonicalPlaceId=381099; 381087 is alias only',
    },
    {
      placeId: 381087,
      label: 'Snæfellsjökull NP (alias)',
      entityType: 'ATTRACTION_AREA',
      canonicalPlaceId: 381099,
      coverageRole: 'SUPPORT',
      notes: 'ALIAS_OF 381099 — excluded from solver / coverage scoring',
    },
    {
      placeId: 381086,
      label: 'Djúpalónssandur',
      entityType: 'ATTRACTION',
      coverageRole: 'PRIMARY',
      typicalVisitMinutes: 60,
      representativenessScore: 0.9,
    },
    {
      placeId: 381085,
      label: 'Grundarfjörður',
      entityType: 'TOWN_HUB',
      coverageRole: 'SUPPORT',
      routeRoles: ['OVERNIGHT_HUB', 'SUPPLY_HUB', 'KIRKJUFELL_GATEWAY'],
    },
    {
      placeId: 381049,
      label: 'Grundarfjörður Guesthouse',
      entityType: 'LODGING',
      routeRoles: ['OVERNIGHT_HUB'],
      coverageRole: 'SUPPORT',
    },
    {
      placeId: 381546,
      label: 'Stykkishólmur fuel',
      entityType: 'SERVICE',
      routeRoles: ['SUPPLY_HUB'],
      coverageRole: 'SUPPORT',
    },
    {
      experienceProductId: 'exp_whale_watching_west',
      label: 'Whale watching (west / Stykkishólmur)',
      entityType: 'EXPERIENCE_PRODUCT',
      bookingRequired: true,
      durationMinutes: 180,
      seasonalAvailability: ['summer', 'shoulder'],
    },
  ],
  relations: [
    {
      groupId: 'snae_np_alias',
      relationType: 'ALIAS_OF',
      memberPlaceIds: [381099, 381087],
      notes: '381087 → canonical 381099',
    },
  ],
  planningPolicy: {
    minRecommendedDays: 1,
    idealRecommendedDays: 2,
    directionHints: [
      'reykjavik_to_grundarfjordur',
      'peninsula_loop_kirkjufell_park_beach',
    ],
    maxCoreAnchorsPerDay: 3,
    seasonalBufferMinutes: 30,
  },
  sourceRefs: ['catalog:IS_SNAEFELLSNES'],
};

/** Wizard region `north` — attraction-ready but day-planning must use subregions. */
export const NORTH_ICELAND_PACK: IcelandRegionPlanningPack = {
  packId: 'north',
  wizardRegionIds: ['north'],
  version: '2026-07-qa1',
  status: 'ACTIVE',
  coverageStatus: 'ATTRACTION_READY',
  regionalGoldenSetReady: true,
  displayName: 'North Iceland',
  entities: [
    {
      placeId: 381097,
      label: 'Akureyri',
      entityType: 'TOWN_HUB',
      coverageRole: 'SECONDARY',
      routeRoles: ['OVERNIGHT_HUB', 'SUPPLY_HUB', 'ENTRY_GATEWAY'],
      typicalVisitMinutes: 90,
      representativenessScore: 0.75,
    },
    {
      placeId: 381096,
      label: 'Goðafoss',
      entityType: 'ATTRACTION',
      coverageRole: 'PRIMARY',
      typicalVisitMinutes: 45,
      representativenessScore: 0.95,
    },
    {
      placeId: 381107,
      label: 'Mývatn',
      entityType: 'ATTRACTION_AREA',
      coverageRole: 'PRIMARY',
      typicalVisitMinutes: 120,
      representativenessScore: 1,
    },
    {
      placeId: 381091,
      label: 'Mývatn Nature Baths',
      entityType: 'ATTRACTION',
      coverageRole: 'SECONDARY',
      typicalVisitMinutes: 90,
      representativenessScore: 0.8,
    },
    {
      placeId: 381095,
      label: 'Dettifoss',
      entityType: 'ATTRACTION',
      coverageRole: 'PRIMARY',
      typicalVisitMinutes: 75,
      representativenessScore: 0.92,
      seasonalAvailability: ['summer', 'shoulder'],
      vehicleConstraints: ['long_gravel_ok'],
      notes: 'PRIMARY candidate only — road/vehicle gates decide inclusion',
    },
    {
      placeId: 381050,
      label: 'Akureyri Backpackers',
      entityType: 'LODGING',
      routeRoles: ['OVERNIGHT_HUB'],
      coverageRole: 'SUPPORT',
    },
    {
      placeId: 381051,
      label: 'Mývatn Nature Baths Guesthouse',
      entityType: 'LODGING',
      routeRoles: ['OVERNIGHT_HUB'],
      coverageRole: 'SUPPORT',
    },
    {
      placeId: 381056,
      label: 'Mývatn Nature Baths visitor centre',
      entityType: 'SERVICE',
      routeRoles: ['REST_STOP'],
      coverageRole: 'SUPPORT',
    },
    {
      placeId: 381057,
      label: 'Akureyri car rental & repair',
      entityType: 'SERVICE',
      routeRoles: ['SUPPLY_HUB'],
      coverageRole: 'SUPPORT',
    },
    {
      experienceProductId: 'exp_myvatn_bath_admission',
      label: 'Mývatn Nature Baths admission',
      entityType: 'EXPERIENCE_PRODUCT',
      meetingPlaceId: 381091,
      regionAnchorPlaceId: 381091,
      bookingRequired: true,
      durationMinutes: 90,
      seasonalAvailability: ['all'],
    },
  ],
  relations: [],
  subregions: [
    {
      subregionId: 'north_west',
      displayName: 'Akureyri / Goðafoss',
      entityPlaceIds: [381097, 381096, 381050, 381057],
      minRecommendedDays: 1,
      idealRecommendedDays: 1,
      directionHints: ['akureyri_hub', 'godafoss_side_trip'],
    },
    {
      subregionId: 'north_east_myvatn',
      displayName: 'Mývatn basin',
      entityPlaceIds: [381107, 381091, 381051, 381056],
      minRecommendedDays: 1,
      idealRecommendedDays: 1,
      directionHints: ['myvatn_loop'],
    },
    {
      subregionId: 'diamond_circle',
      displayName: 'Diamond Circle (incl. Dettifoss)',
      entityPlaceIds: [381095, 381107],
      minRecommendedDays: 1,
      idealRecommendedDays: 2,
      directionHints: ['dettifoss_when_roads_open'],
      notes: 'Do not auto-merge with north_west into one day',
    },
  ],
  planningPolicy: {
    minRecommendedDays: 2,
    idealRecommendedDays: 3,
    requireSubregionDayScope: true,
    maxCoreAnchorsPerDay: 2,
    seasonalBufferMinutes: 45,
    directionHints: ['use_subregions_not_whole_north'],
  },
  sourceRefs: ['catalog:IS_NORTH'],
  notes: ['Wizard region stays `north`; day generation must scope to one subregion.'],
};

/**
 * East Fjords — CORRIDOR_ONLY until real attractions land in Catalog.
 * Not an attraction golden set.
 */
export const EAST_FJORDS_PACK: IcelandRegionPlanningPack = {
  packId: 'east_fjords',
  wizardRegionIds: ['east_fjords'],
  version: '2026-07-qa1',
  status: 'ACTIVE',
  coverageStatus: 'CORRIDOR_ONLY',
  regionalGoldenSetReady: false,
  displayName: 'East Fjords (corridor)',
  entities: [
    {
      placeId: 381047,
      label: 'Höfn',
      entityType: 'TOWN_HUB',
      coverageRole: 'SUPPORT',
      routeRoles: ['ENTRY_GATEWAY', 'OVERNIGHT_HUB'],
      notes:
        'SE entry from south_coast_east.exit — not an East Fjords attraction PRIMARY',
    },
    {
      placeId: 381486,
      label: 'N1 Egilsstaðir',
      entityType: 'SERVICE',
      routeRoles: ['SUPPLY_HUB'],
      coverageRole: 'SUPPORT',
    },
    {
      placeId: 381487,
      label: 'N1 Djúpivogur',
      entityType: 'SERVICE',
      routeRoles: ['SUPPLY_HUB'],
      coverageRole: 'SUPPORT',
    },
    {
      placeId: 381485,
      label: 'Orkan Seyðisfjörður',
      entityType: 'SERVICE',
      routeRoles: ['SUPPLY_HUB'],
      coverageRole: 'SUPPORT',
    },
    {
      placeId: 381075,
      label: 'N1 Höfn',
      entityType: 'SERVICE',
      routeRoles: ['SUPPLY_HUB'],
      coverageRole: 'SUPPORT',
    },
  ],
  relations: [],
  planningPolicy: {
    minRecommendedDays: 1,
    idealRecommendedDays: 2,
    directionHints: ['corridor_fuel_overnight_only'],
    maxCoreAnchorsPerDay: 0,
  },
  sourceRefs: ['catalog:east_thin'],
  notes: [
    'coverageStatus=CORRIDOR_ONLY; regionalGoldenSetReady=false',
    'Minimum attractions to promote: Vestrahorn/Stokksnes, Hengifoss, Seyðisfjörður visit node, Djúpivogur cultural node',
  ],
};

export const WESTFJORDS_PACK: IcelandRegionPlanningPack = {
  packId: 'westfjords',
  wizardRegionIds: ['westfjords'],
  version: '2026-07-qa1',
  status: 'ACTIVE',
  coverageStatus: 'ATTRACTION_READY',
  regionalGoldenSetReady: true,
  displayName: 'Westfjords',
  entities: [
    {
      placeId: 381458,
      label: 'Dynjandi',
      entityType: 'ATTRACTION',
      coverageRole: 'PRIMARY',
      typicalVisitMinutes: 75,
      representativenessScore: 1,
      aliasPlaceIds: [381290],
    },
    {
      placeId: 381290,
      label: 'Dynjandi Waterfall (alias)',
      entityType: 'ATTRACTION',
      canonicalPlaceId: 381458,
      coverageRole: 'SUPPORT',
      notes: 'ALIAS_OF 381458',
    },
    {
      placeId: 381460,
      label: 'Látrabjarg',
      entityType: 'ATTRACTION',
      coverageRole: 'PRIMARY',
      typicalVisitMinutes: 90,
      representativenessScore: 0.95,
      seasonalAvailability: ['summer', 'shoulder'],
      vehicleConstraints: ['gravel_ok'],
    },
    {
      placeId: 381299,
      label: 'Rauðasandur',
      entityType: 'ATTRACTION',
      coverageRole: 'PRIMARY',
      typicalVisitMinutes: 60,
      representativenessScore: 0.85,
    },
    {
      placeId: 381304,
      label: 'Hellulaug',
      entityType: 'ATTRACTION',
      coverageRole: 'SECONDARY',
      typicalVisitMinutes: 45,
      representativenessScore: 0.65,
    },
    {
      placeId: 381459,
      label: 'Patreksfjörður',
      entityType: 'TOWN_HUB',
      coverageRole: 'SUPPORT',
      routeRoles: ['ENTRY_GATEWAY', 'SUPPLY_HUB', 'OVERNIGHT_HUB'],
    },
    {
      placeId: 381288,
      label: 'Ísafjörður',
      entityType: 'TOWN_HUB',
      coverageRole: 'SECONDARY',
      routeRoles: ['OVERNIGHT_HUB', 'SUPPLY_HUB'],
      typicalVisitMinutes: 60,
      representativenessScore: 0.7,
    },
    {
      placeId: 381301,
      label: 'Arctic Fox Centre',
      entityType: 'ATTRACTION',
      coverageRole: 'SECONDARY',
      typicalVisitMinutes: 45,
    },
    {
      placeId: 381303,
      label: 'Westfjords Heritage Museum',
      entityType: 'ATTRACTION',
      coverageRole: 'SUPPORT',
      routeRoles: ['WEATHER_FALLBACK_HUB'],
      typicalVisitMinutes: 45,
      notes:
        'Indoor fallback — needs openingHours/seasonality/expectedDuration in Catalog before auto-replace',
    },
    {
      placeId: 381528,
      label: 'N1 Patreksfjörður',
      entityType: 'SERVICE',
      routeRoles: ['SUPPLY_HUB'],
      coverageRole: 'SUPPORT',
    },
  ],
  relations: [
    {
      groupId: 'wf_dynjandi_alias',
      relationType: 'ALIAS_OF',
      memberPlaceIds: [381458, 381290],
    },
    {
      groupId: 'wf_sw_coast',
      relationType: 'CO_VISIT_CLUSTER',
      memberPlaceIds: [381460, 381299],
      notes: 'SW Westfjords cluster — soft; not same-day forced with Dynjandi',
    },
  ],
  subregions: [
    {
      subregionId: 'westfjords_southwest',
      displayName: 'SW Westfjords',
      entityPlaceIds: [381459, 381460, 381299, 381304, 381528],
      minRecommendedDays: 1,
      idealRecommendedDays: 2,
      directionHints: ['patreks_latrabjarg_raudisandur'],
    },
    {
      subregionId: 'westfjords_central_north',
      displayName: 'Central / north Westfjords',
      entityPlaceIds: [381458, 381288, 381301, 381303],
      minRecommendedDays: 1,
      idealRecommendedDays: 2,
      directionHints: ['dynjandi_isafjordur'],
    },
  ],
  planningPolicy: {
    minRecommendedDays: 2,
    idealRecommendedDays: 3,
    requireSubregionDayScope: true,
    maxCoreAnchorsPerDay: 2,
    seasonalBufferMinutes: 60,
  },
  sourceRefs: ['catalog:IS_WESTFJORDS'],
};

export const HIGHLANDS_PACK: IcelandRegionPlanningPack = {
  packId: 'highlands',
  wizardRegionIds: ['highlands'],
  version: '2026-07-qa1',
  status: 'ACTIVE',
  coverageStatus: 'ATTRACTION_READY',
  regionalGoldenSetReady: true,
  displayName: 'Highlands',
  entities: [
    {
      placeId: 381108,
      label: 'Landmannalaugar',
      entityType: 'ATTRACTION_AREA',
      coverageRole: 'PRIMARY',
      typicalVisitMinutes: 180,
      representativenessScore: 1,
      seasonalAvailability: ['summer'],
      vehicleConstraints: ['4wd_required', 'f_road'],
      suitableTripStyles: ['adventure', 'hiking'],
    },
    {
      placeId: 381127,
      label: 'Landmannalaugar Hot Spring',
      entityType: 'ATTRACTION',
      coverageRole: 'SECONDARY',
      parentPlaceId: 381108,
      typicalVisitMinutes: 60,
      seasonalAvailability: ['summer'],
      notes: 'Child of Landmannalaugar — no double coverage',
    },
    {
      placeId: 381109,
      label: 'Þórsmörk',
      entityType: 'ROUTE_ANCHOR',
      coverageRole: 'SUPPORT',
      typicalVisitMinutes: 30,
      seasonalAvailability: ['summer'],
      routeRoles: ['ENTRY_GATEWAY'],
      notes:
        'Meeting / region anchor only — self-drive river crossings are not auto-scheduled; use guided experience',
    },
    {
      placeId: 381111,
      label: 'Askja',
      entityType: 'ATTRACTION_AREA',
      coverageRole: 'PRIMARY',
      typicalVisitMinutes: 240,
      representativenessScore: 0.88,
      seasonalAvailability: ['summer'],
      vehicleConstraints: ['4wd_required', 'f_road', 'remote_fuel'],
    },
    {
      placeId: 381122,
      label: 'Víti crater',
      entityType: 'ATTRACTION',
      coverageRole: 'SECONDARY',
      parentPlaceId: 381111,
      typicalVisitMinutes: 60,
    },
    {
      placeId: 381110,
      label: 'Sprengisandur Highland Road',
      entityType: 'ROUTE_ANCHOR',
      coverageRole: 'SUPPORT',
      typicalVisitMinutes: 30,
      seasonalAvailability: ['summer'],
      vehicleConstraints: ['4wd_required', 'f_road'],
    },
    {
      experienceProductId: 'exp_landmannalaugar_superjeep',
      label: 'Landmannalaugar super jeep / guided highland day',
      entityType: 'EXPERIENCE_PRODUCT',
      meetingPlaceId: 381108,
      regionAnchorPlaceId: 381108,
      bookingRequired: true,
      durationMinutes: 480,
      seasonalAvailability: ['summer'],
      notes: 'transportMode GUIDED_SUPER_JEEP — never reuse placeId 381108',
    },
    {
      experienceProductId: 'exp_thorsmork_superjeep',
      label: 'Þórsmörk super jeep / guided highland day',
      entityType: 'EXPERIENCE_PRODUCT',
      meetingPlaceId: 381109,
      regionAnchorPlaceId: 381109,
      bookingRequired: true,
      durationMinutes: 480,
      seasonalAvailability: ['summer'],
      notes:
        'Guided access replaces self-drive river_crossing hard gate — never reuse placeId 381109 as activity id',
    },
  ],
  relations: [
    {
      groupId: 'hl_landmannalaugar_spring',
      relationType: 'PARENT_CHILD',
      memberPlaceIds: [381108, 381127],
    },
    {
      groupId: 'hl_askja_viti',
      relationType: 'PARENT_CHILD',
      memberPlaceIds: [381111, 381122],
    },
  ],
  subregions: [
    {
      subregionId: 'highlands_south_landmannalaugar',
      displayName: 'Landmannalaugar',
      entityPlaceIds: [381108, 381127],
      minRecommendedDays: 1,
      idealRecommendedDays: 2,
      involvesFRoad: true,
      directionHints: ['summer_only', '4wd_or_tour'],
    },
    {
      subregionId: 'highlands_south_thorsmork',
      displayName: 'Þórsmörk',
      entityPlaceIds: [381109],
      minRecommendedDays: 1,
      idealRecommendedDays: 2,
      involvesFRoad: true,
      notes: 'River-crossing / transfer gates required',
    },
    {
      subregionId: 'highlands_north_askja',
      displayName: 'Askja',
      entityPlaceIds: [381111, 381122],
      minRecommendedDays: 1,
      idealRecommendedDays: 2,
      involvesFRoad: true,
    },
    {
      subregionId: 'highlands_crossing_sprengisandur',
      displayName: 'Sprengisandur crossing',
      entityPlaceIds: [381110],
      minRecommendedDays: 1,
      idealRecommendedDays: 1,
      involvesFRoad: true,
      notes: 'Corridor crossing — not an attraction day by default',
    },
  ],
  planningPolicy: {
    minRecommendedDays: 2,
    idealRecommendedDays: 3,
    requireSubregionDayScope: true,
    involvesFRoad: true,
    maxCoreAnchorsPerDay: 1,
    seasonalBufferMinutes: 90,
    directionHints: ['never_mix_askja_and_thorsmork_same_day'],
  },
  sourceRefs: ['catalog:IS_HIGHLANDS'],
};

/** Corridor meta — no geographic golden set */
export const RING_ROAD_CORRIDOR: IcelandRegionPlanningPack = {
  packId: 'ring_road',
  wizardRegionIds: ['ring_road'],
  version: '2026-07-qa1',
  status: 'ACTIVE',
  coverageStatus: 'CORRIDOR_ONLY',
  regionalGoldenSetReady: false,
  displayName: 'Ring Road (corridor)',
  entities: [
    {
      label: 'Ring Road corridor',
      entityType: 'CORRIDOR',
      coverageRole: 'SUPPORT',
      notes: 'References other region packs — does not own POIs',
    },
  ],
  relations: [],
  planningPolicy: {
    directionHints: [
      'continuity',
      'overnight_spacing',
      'fuel_coverage',
      'referenced_regions',
    ],
  },
  sourceRefs: [],
  notes: [
    'coverageMode=REFERENCED_REGIONS',
    'May reference: golden_circle, south_coast_*, east_fjords, north, snaefellsnes, westfjords',
  ],
};

export const ICELAND_REGION_PLANNING_PACKS: IcelandRegionPlanningPack[] = [
  REYKJAVIK_ARRIVAL_PACK,
  GOLDEN_CIRCLE_PACK,
  SOUTH_COAST_WEST_PACK,
  SOUTH_COAST_EAST_PACK,
  SNAEFELLSNES_PACK,
  NORTH_ICELAND_PACK,
  EAST_FJORDS_PACK,
  WESTFJORDS_PACK,
  HIGHLANDS_PACK,
  RING_ROAD_CORRIDOR,
];

export const ICELAND_REGION_PLANNING_PACK_BY_ID: Record<
  string,
  IcelandRegionPlanningPack
> = Object.fromEntries(ICELAND_REGION_PLANNING_PACKS.map((p) => [p.packId, p]));
