#!/usr/bin/env npx tsx
/**
 * ETA-L2-CANARY-01 — enable Selected Trips authoritative scheduling (process-local env file).
 *
 *   npm run lab:eta-l2-enable-selected-trips -- --trip-ids=trip-a,trip-b
 *   npm run lab:eta-l2-enable-selected-trips -- --trip-ids=trip-a --apply-local-check
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'fs';
import { join } from 'path';
import {
  evaluateTravelEtaL2AuthorityGate,
  resolveTravelEtaAuthorityForTrip,
} from '../travel-eta-l2-authority.gate';

const OPS_ROOT = join(process.cwd(), 'src/transport/ops');
const LAB_OUT = join(OPS_ROOT, 'lab', '.out');

function parseTripIds(): string[] {
  const arg = process.argv.find((a) => a.startsWith('--trip-ids='));
  if (arg) {
    return arg
      .slice('--trip-ids='.length)
      .split(',')
      .map((s) => s.trim())
      .filter(Boolean);
  }
  const envIds = (process.env.TRAVEL_ETA_L2_SELECTED_TRIP_IDS ?? '')
    .split(',')
    .map((s) => s.trim())
    .filter(Boolean);
  if (envIds.length) return envIds;

  const wlPath = join(OPS_ROOT, 'travel-eta-l2-selected-trips.whitelist.json');
  if (existsSync(wlPath)) {
    try {
      const wl = JSON.parse(readFileSync(wlPath, 'utf8')) as { tripIds?: string[] };
      return wl.tripIds ?? [];
    } catch {
      return [];
    }
  }
  return [];
}

function main(): number {
  const tripIds = parseTripIds();
  if (tripIds.length === 0) {
    console.error(
      'FAIL: provide --trip-ids=id1,id2 or TRAVEL_ETA_L2_SELECTED_TRIP_IDS or whitelist tripIds',
    );
    return 1;
  }

  if (!existsSync(LAB_OUT)) mkdirSync(LAB_OUT, { recursive: true });

  const enablePath = join(LAB_OUT, 'eta-l2-selected-trips-enable.env');
  const body = [
    '# Generated by lab:eta-l2-enable-selected-trips — staging/host apply',
    '# Kill: TRAVEL_ETA_L2_KILL_SWITCH=1  OR  TRAVEL_ETA_L2_CANARY_STAGE=shadow',
    'TRAVEL_ETA_L2_CANARY_STAGE=selected_trips',
    'TRAVEL_ETA_L2_AUTHORITY_APPROVED=1',
    `TRAVEL_ETA_L2_SELECTED_TRIP_IDS=${tripIds.join(',')}`,
    'TRAVEL_ETA_L2_KILL_SWITCH=0',
    '',
  ].join('\n');
  writeFileSync(enablePath, body, 'utf8');

  const wlOutPath = join(LAB_OUT, 'travel-eta-l2-selected-trips.whitelist.json');
  const wlPayload = {
    schemaId: 'tripnara.travel_eta_l2_selected_trips@v1' as const,
    tripIds,
    destinations: ['IS_highlands', 'F208', 'F35', 'Route1_control'],
    notes: `Enabled ${new Date().toISOString()} via lab:eta-l2-enable-selected-trips`,
  };
  writeFileSync(wlOutPath, JSON.stringify(wlPayload, null, 2) + '\n', 'utf8');

  const writeRepoWhitelist = process.argv.includes('--write-whitelist');
  const wlPath = join(OPS_ROOT, 'travel-eta-l2-selected-trips.whitelist.json');
  if (writeRepoWhitelist) {
    writeFileSync(wlPath, JSON.stringify(wlPayload, null, 2) + '\n', 'utf8');
  }

  const applyLocal = process.argv.includes('--apply-local-check');
  if (applyLocal) {
    process.env.TRAVEL_ETA_L2_CANARY_STAGE = 'selected_trips';
    process.env.TRAVEL_ETA_L2_AUTHORITY_APPROVED = '1';
    process.env.TRAVEL_ETA_L2_SELECTED_TRIP_IDS = tripIds.join(',');
    delete process.env.TRAVEL_ETA_L2_KILL_SWITCH;
  }

  const gate = evaluateTravelEtaL2AuthorityGate({
    goldMatrixPresent: true,
    whitelist: wlPayload,
  });
  const sampleTrip = tripIds[0];
  const authority = resolveTravelEtaAuthorityForTrip({
    tripId: sampleTrip,
    countryCode: 'IS',
    gate,
    whitelist: wlPayload,
  });
  const outsider = resolveTravelEtaAuthorityForTrip({
    tripId: 'not-on-whitelist',
    gate,
    whitelist: wlPayload,
  });

  const ok =
    gate.authoritativePromotion &&
    authority === 'AUTHORITATIVE' &&
    outsider === 'SHADOW' &&
    !gate.killSwitch;

  console.log(
    JSON.stringify(
      {
        ok,
        enableEnvFile: enablePath.replace(`${process.cwd()}/`, ''),
        whitelistOut: wlOutPath.replace(`${process.cwd()}/`, ''),
        repoWhitelistUpdated: writeRepoWhitelist,
        tripIds,
        gate: {
          stage: gate.canaryStage,
          releaseAuthorized: gate.releaseAuthorized,
          authoritativePromotion: gate.authoritativePromotion,
          blockedReasons: gate.blockedReasons,
        },
        sample: { tripId: sampleTrip, authority },
        outsiderAuthority: outsider,
        hostApply: [
          `set -a; source ${enablePath.replace(`${process.cwd()}/`, '')}; set +a`,
          'restart API so TravelSegmentEnrichmentService picks up env',
          'npm run lab:eta-l2-kill-switch-drill',
        ],
      },
      null,
      2,
    ),
  );

  return ok ? 0 : 1;
}

process.exit(main());
