// src/skills/skills.tokens.ts
// String tokens to avoid tsx/ESM module-identity issues with class-based DI tokens.

export const SKILL_DEM_GET_PROFILE = 'SKILL_DEM_GET_PROFILE';

export const SKILL_DECISION_ABU_CHECK = 'SKILL_DECISION_ABU_CHECK';
export const SKILL_DECISION_DRDRE_PACE = 'SKILL_DECISION_DRDRE_PACE';
export const SKILL_DECISION_NEPTUNE_REPAIR = 'SKILL_DECISION_NEPTUNE_REPAIR';

export const SKILL_ROUTE_DIRECTION_PICK_FOR_INTENT = 'SKILL_ROUTE_DIRECTION_PICK_FOR_INTENT';

export const SKILL_READINESS_GENERATE_CHECKLIST = 'SKILL_READINESS_GENERATE_CHECKLIST';

export const SKILL_COUNTRY_PACK_NEW_SKELETON = 'SKILL_COUNTRY_PACK_NEW_SKELETON';
export const SKILL_COUNTRY_PACK_VALIDATE = 'SKILL_COUNTRY_PACK_VALIDATE';
export const SKILL_COUNTRY_PACK_GENERATE_REGRESSION_TESTS = 'SKILL_COUNTRY_PACK_GENERATE_REGRESSION_TESTS';


