/** PRD 4.3 Tag Mapping Lexicon — 黑话 → 前端 Chip + 算法联动（顺序优先：越具体越靠前） */

export interface VibeLexiconRule {
  id: string;
  patterns: RegExp[];
  chipLabel: string;
  algorithmNotes?: string;
  contractKey?: string;
  /** 命中后 suppress 的泛化标签 id */
  suppresses?: string[];
}

export const VIBE_TAG_LEXICON: VibeLexiconRule[] = [
  {
    id: 'surf_skydive',
    patterns: [/冲浪/, /跳伞/, /万宁/],
    chipLabel: '🌊 冲浪/跳伞',
    algorithmNotes: 'script=dopamine_escape',
  },
  {
    id: 'beach_edm',
    patterns: [/电音节/, /livehouse|Livehouse/, /喝到断片/],
    chipLabel: '🎵 海滩电音节',
    algorithmNotes: 'script=dopamine_escape',
  },
  {
    id: 'blindbox_follow',
    patterns: [/盲盒/, /带我疯/, /预算无上限/],
    chipLabel: '⚡️ 盲盒跟从',
    algorithmNotes: 'script=dopamine_escape',
  },
  {
    id: 'burn_revival',
    patterns: [/燃尽复活|fundraising|seed 轮|整个人都要燃尽了/],
    chipLabel: '🔥 燃尽复活',
    suppresses: ['deep_relax'],
    algorithmNotes: 'script=dopamine_escape',
  },
  {
    id: 'laugavegur_55km',
    patterns: [/兰格维格|Laugavegur|55\s*公里|55km/i],
    chipLabel: '🏔️ 兰格维格55km',
    algorithmNotes: 'script=iceland_laugavegur_heavy_trek',
  },
  {
    id: 'iceland_volcanic_wilderness',
    patterns: [
      /Landmannalaugar|兰曼纳劳卡|彩色火山|黑色曜石|Þórsmörk|Thorsmork|索斯莫克|冰川河流|荒原/i,
    ],
    chipLabel: '🌋 彩色火山与荒原',
    algorithmNotes: 'script=iceland_laugavegur_heavy_trek',
  },
  {
    id: 'dem_blind_nav',
    patterns: [
      /冰岛.*(DEM|数字高程|离线)/i,
      /(DEM|数字高程).*(冰岛|兰格维格|Laugavegur|内陆)/i,
      /12\.5.*精度.*DEM|DEM.*12\.5/i,
      /离线.*3D.*路线|DEM高程盲导/i,
    ],
    chipLabel: '📡 DEM高程盲导',
    suppresses: ['dem_survey'],
    algorithmNotes: 'script=iceland_laugavegur_heavy_trek',
  },
  {
    id: 'glacier_river_ford',
    patterns: [/冰川.*涉水|强涉水|Fjórðungakvísl|融水涉水|涉水路段/i],
    chipLabel: '🌊 冰川强涉水',
    algorithmNotes: 'script=iceland_laugavegur_heavy_trek',
  },
  {
    id: 'chuanxi_heavy_trek',
    patterns: [/川西.*重装|长坪沟|毕棚沟|贡嘎大环|贡嘎大环线/],
    chipLabel: '🏔️ 川西重装徒步',
    algorithmNotes: 'script=chuanxi_heavy_trek',
  },
  {
    id: 'dem_digital_elevation',
    patterns: [/DEM.*数字高程|数字高程模型|多源卫星路径/],
    chipLabel: '📡 DEM数字高程',
    suppresses: ['dem_survey'],
    algorithmNotes: 'script=chuanxi_heavy_trek',
  },
  {
    id: 'self_supported_camping',
    patterns: [/自负重|自己背负|扎营|不搞.*保姆|马帮全包/],
    chipLabel: '⛺️ 自负重野营',
    contractKey: 'wild_camping',
    algorithmNotes: 'script=chuanxi_heavy_trek',
  },
  {
    id: 'risk_self_managed',
    patterns: [/风险自理|掉链子|Plan B|LNT|无痕山林/],
    chipLabel: '🛡️ 风险自理',
    contractKey: 'hardcore_survival',
    algorithmNotes: 'script=chuanxi_heavy_trek',
  },
  {
    id: 'yubeng_light_retreat',
    patterns: [/雨崩|乌孙古道|天堂湖/, /轻装徒步|轻装/],
    chipLabel: '🪵 雨崩轻装隐居',
    algorithmNotes: 'script=light_trek_dyl_retreat',
  },
  {
    id: 'burnwash_full',
    patterns: [/班味全面净化|满身班味|精神内耗空了/],
    chipLabel: '🧘 班味全面净化',
    suppresses: ['deep_relax', 'burnwash'],
    algorithmNotes: 'script=light_trek_dyl_retreat',
  },
  {
    id: 'starry_bonfire',
    patterns: [/星空|围炉局|客栈里组个局|就着星空/],
    chipLabel: '🌌 星空围炉局',
    algorithmNotes: 'script=light_trek_dyl_retreat',
  },
  {
    id: 'trail_fast_ascent',
    patterns: [/山野速攀|速攀|Fast\s*&\s*Light|百公里越野|浙西三尖|十里琅珰/],
    chipLabel: '🏃 山野速攀',
    algorithmNotes: 'script=weekend_fast_light_trek',
  },
  {
    id: 'hr_max_out',
    patterns: [/心率.*160|心率拉满|物理痛苦/],
    chipLabel: '⚡️ 心率拉满',
    algorithmNotes: 'script=weekend_fast_light_trek',
  },
  {
    id: 'elite_silence',
    patterns: [/高阶沉默|边界感|无效社交|默契的沉默|不聊大厂八卦|不用互相拍照/],
    chipLabel: '🤐 高阶沉默',
    algorithmNotes: 'script=weekend_fast_light_trek',
  },
  {
    id: 'basecamp_craft_beer',
    patterns: [/下山.*精酿|山脚小酒馆|精酿原地解散/],
    chipLabel: '🍺 下山精酿',
    algorithmNotes: 'script=weekend_fast_light_trek',
  },
  {
    id: 'polar_expedition',
    patterns: [/南极/, /斯瓦尔巴|Svalbard/, /极圈科考|科考站/],
    chipLabel: '❄️ 极圈科考',
    algorithmNotes: 'script=polar_expedition',
  },
  {
    id: 'extreme_trek',
    patterns: [/冰川/, /极昼徒步/, /无人冰原/],
    chipLabel: '🏔️ 极限徒步',
    algorithmNotes: 'script=polar_expedition',
  },
  {
    id: 'dem_survey',
    patterns: [/DEM.*高程|高程数据设备/],
    chipLabel: '📡 DEM高程采集',
    algorithmNotes: 'script=polar_expedition',
  },
  {
    id: 'extreme_cold_survival',
    patterns: [/极寒/, /失温/, /暴风雪/],
    chipLabel: '🥶 极端环境生存',
    contractKey: 'hardcore_survival',
    algorithmNotes: 'script=polar_expedition',
  },
  {
    id: 'industrial_ruins',
    patterns: [/工业废墟/, /老工业基地/, /鲁尔区/],
    chipLabel: '🏭 工业废墟',
    algorithmNotes: 'script=industrial_ruins',
  },
  {
    id: 'aps_mes',
    patterns: [/APS|MES|制造数字化|智能工厂/],
    chipLabel: '📊 APS/MES数字化',
    algorithmNotes: 'script=industrial_ruins',
  },
  {
    id: 'steel_behemoth',
    patterns: [/钢铁厂/, /钢铁巨兽/, /造船厂/],
    chipLabel: '⚙️ 钢铁巨兽',
    algorithmNotes: 'script=industrial_ruins',
  },
  {
    id: 'ruins_trace',
    patterns: [/遗迹溯源/, /废墟.*溯源|溯源自驾/],
    chipLabel: '🕵️ 遗迹溯源',
    algorithmNotes: 'script=industrial_ruins',
  },
  {
    id: 'bali_nomad',
    patterns: [/巴厘岛|清迈|乌布/, /数字游牧|数字游民社区/],
    chipLabel: '🌴 巴厘岛游牧',
    suppresses: ['dali_nomad'],
    algorithmNotes: 'script=island_geek_hackathon',
  },
  {
    id: 'indie_hacking',
    patterns: [/Agent|开源项目|独立开源|写自己的.*项目|黑客松/i],
    chipLabel: '⚡️ 独立项目Hacking',
    contractKey: 'vibe_coding',
    algorithmNotes: 'script=island_geek_hackathon',
  },
  {
    id: 'coastal_rush',
    patterns: [/海滩.*狂飙|沿海.*狂飙|路虎狂飙/],
    chipLabel: '🏎️ 沿海狂飙',
    algorithmNotes: 'script=island_geek_hackathon',
  },
  {
    id: 'cofounder_blindbox',
    patterns: [/Co-founder|Co-founder|原地组队|第一行代码/],
    chipLabel: '🤝 Co-founder盲盒',
    algorithmNotes: 'script=island_geek_hackathon',
  },
  {
    id: 'anji_dna',
    patterns: [/安吉.*DNA|DNA 数字游民公社/],
    chipLabel: '⛰️ 安吉DNA游牧',
    algorithmNotes: 'script=mountain_dyl_retreat',
  },
  {
    id: 'dyl_life_design',
    patterns: [/DYL|设计你的人生|人生转型复盘/],
    chipLabel: '📐 DYL人生设计',
    algorithmNotes: 'script=mountain_dyl_retreat',
  },
  {
    id: 'valley_bonfire',
    patterns: [/围炉煮茶|山谷.*露营|看日落/],
    chipLabel: '⛺️ 山谷围炉',
    contractKey: 'wild_camping',
    algorithmNotes: 'script=mountain_dyl_retreat',
  },
  {
    id: 'burnwash',
    patterns: [/班味净洗|OKR.*燃尽|被大厂的高压|互相疗愈/],
    chipLabel: '🧘 班味净洗',
    suppresses: ['deep_relax'],
    algorithmNotes: 'script=mountain_dyl_retreat',
  },
  {
    id: 'dali_nomad',
    patterns: [/大理.*游民|游民社区|变蕉|数字游民|大理的游民/],
    chipLabel: '🌾 大理变蕉游牧',
    suppresses: ['deep_relax', 'mindless_float', 'cross_energy'],
    algorithmNotes: 'script3=non_mainstream_collision_dali',
  },
  {
    id: 'cangshan_mushroom',
    patterns: [/苍山.*捡菌|捡菌子|捡菌|菌子/],
    chipLabel: '🍄 苍山捡菌子',
    algorithmNotes: 'script3=non_mainstream_collision_dali',
  },
  {
    id: 'detach_floating',
    patterns: [/悬浮感|剥离逻辑|物理世界|真实感知|虚拟.*数据符号|符号悬浮|具体的真实生活/],
    chipLabel: '🎨 剥离悬浮感',
    suppresses: ['deep_learning', 'cross_energy', 'deep_relax'],
    algorithmNotes: 'script3=non_mainstream_collision_dali',
  },
  {
    id: 'wild_craftsman',
    patterns: [/野生搭子|手艺人|陶艺师|陶艺|流浪歌手|完全不是互联网|不是互联网圈/],
    chipLabel: '🧶 野生手艺对撞',
    suppresses: ['cross_energy', 'credential_tier'],
    algorithmNotes: 'script3=non_mainstream_collision_dali',
  },
  {
    id: 'deep_relax',
    patterns: [/躺尸|疗愈|发呆|看云|不赶任何景点|班味|强迫症/],
    chipLabel: '🧘 深度松弛',
    algorithmNotes: 'tripMoodTag=healing 权重提升',
  },
  {
    id: 'cross_energy',
    patterns: [/跨界高能|人形种草|能量要高、要好玩/],
    chipLabel: '🎨 跨界高能',
  },
  {
    id: 'music_bar',
    patterns: [/民谣|酒馆|听民谣|音乐小酒馆/],
    chipLabel: '🎵 音乐小酒馆',
    contractKey: 'music_vibe',
  },
  {
    id: 'mindless_float',
    patterns: [/无脑放空|纯躺|咖啡馆发呆/],
    chipLabel: '☁️ 无脑放空',
  },
  {
    id: 'deep_learning',
    patterns: [/看历史|逛遗迹|人文|深度共学|博物馆/],
    chipLabel: '🏛️ 深度共学型',
  },
  {
    id: 'extreme_adventure',
    patterns: [/跳伞/, /直升机滑雪/, /直升机/, /高空/, /极限运动/, /高强度/],
    chipLabel: '🪂 极限 Adrenaline',
    contractKey: 'extreme_adventure',
    algorithmNotes: 'tripMoodTag=adventure 权重提升',
  },
  {
    id: 'luxury_tier',
    patterns: [/顶级品质/, /人均\s*\d+\s*[wW万]/, /\d+\s*[wW万]\s*往上/, /奢华/, /顶配/, /托关系.*订/],
    chipLabel: '💎 高净值顶配',
    contractKey: 'luxury_tier',
    algorithmNotes: '高预算 luxury 场景，提升圈层匹配权重',
  },
  {
    id: 'captain_full_service',
    patterns: [
      /服从指挥/,
      /不需要你?动脑子/,
      /别对路线指手画脚/,
      /都.*订好/,
      /闭眼跟/,
      /(?:行程|安排|带队|指挥).*全包/,
      /全包(?:行程|安排|带队|指挥)/,
    ],
    chipLabel: '🎯 队长全包指挥',
    contractKey: 'captain_full_service',
    algorithmNotes: 'teamworkStyle=full_managed 权重提升',
  },
  {
    id: 'executive_circle',
    patterns: [/高管/, /金融圈/, /战投/, /VP|总监/i],
    chipLabel: '🏦 高管圈层',
    contractKey: 'executive_circle',
    algorithmNotes: 'industry_preference 金融/咨询加权',
  },
  {
    id: 'hardcore_offroad',
    patterns: [/越野/, /无人区/, /陷车/, /爆胎/, /扳手/, /硬核.*自驾/, /真自驾越野/],
    chipLabel: '🛞 硬核越野自驾',
    contractKey: 'hardcore_offroad',
    suppresses: ['self_drive_tour'],
    algorithmNotes: 'travelMode=self_drive + 救援/换胎硬件权重提升',
  },
  {
    id: 'hardcore_survival',
    patterns: [
      /野外生存/,
      /断网/,
      /没信号/,
      /条件比较艰苦/,
      /不搞精致/,
      /精致露营/,
      /温室里的花朵/,
      /温室/,
    ],
    chipLabel: '🏔️ 硬核野外生存',
    contractKey: 'hardcore_survival',
    suppresses: ['wild_camping'],
    algorithmNotes: '断网/无信号场景，降低精致消费权重',
  },
  {
    id: 'stem_mechanic',
    patterns: [/理工科/, /动手能力/, /硬核老司机/, /提着扳手/, /换胎/],
    chipLabel: '🔧 硬核老司机/换胎副手',
    algorithmNotes: '拼图优先 ISTP/INTP 机械补位',
  },
  {
    id: 'sesame_trust',
    patterns: [/芝麻分/, /芝麻信用/, /芝麻.*极佳/],
    chipLabel: '🛡️ 极高芝麻授信',
    algorithmNotes: '触发 sesame Hard Gate + 履约风控',
  },
  {
    id: 'self_drive_tour',
    patterns: [/自驾/, /环游/, /公路旅行/, /开车环/],
    chipLabel: '🏎️ 自驾环游',
    algorithmNotes: 'travelMode=self_drive 权重提升',
  },
  {
    id: 'cooking_partner',
    patterns: [/做饭/, /炊事/, /穷游/, /省着花/, /省钱/, /一起买菜/, /精打细算/],
    chipLabel: '🍳 炊事合伙人',
    contractKey: 'cooking_partner',
    algorithmNotes: '激活行中账目轧差托管',
  },
  {
    id: 'wild_camping',
    patterns: [/露营/, /扎营/, /帐篷/],
    chipLabel: '⛺️ 荒野露营',
    contractKey: 'wild_camping',
  },
  {
    id: 'vibe_coding',
    patterns: [/vibe\s*coding/i, /写代码/, /做项目/, /搞开发/, /coding/],
    chipLabel: '⚡️ Vibe Coding',
    contractKey: 'vibe_coding',
    algorithmNotes: '降低社交能耗，提高电源/网络硬件权重',
  },
  {
    id: 'music_vibe',
    patterns: [/唱歌/, /音乐/, /弹唱/, /live/],
    chipLabel: '🎵 音乐狂欢',
    contractKey: 'music_vibe',
  },
  {
    id: 'credential_tier',
    patterns: [/靠谱/, /不掉链子/, /大厂/, /高学历/, /硕士/, /985/, /211/],
    chipLabel: '🛡️ 职层高授信',
    contractKey: 'credential_tier',
    algorithmNotes: '触发学信网/企业邮箱二度人脉过滤',
  },
  {
    id: 'co_creation',
    patterns: [/一起策划/, /分工/, /合伙/, /共建/, /民主/],
    chipLabel: '🤝 一起策划',
  },
];
