#!/usr/bin/env bash
# Tier C — LEGACY_DEFAULT: full legacy authority.
# See: src/decision-runtime/p4-phase/LEGACY_FALLBACK_RUNBOOK.md
set -euo pipefail
export DECISION_RUNTIME_MODE=LEGACY
export CONSTRAINT_GATEWAY_MODE=OFF
export CONSTRAINT_EVALUATION_GATEWAY_ENABLED=0
export CANONICAL_FULL_PLAN_SELECTION=0
export CANONICAL_EXECUTION_ENABLED=0
export DECISION_TRIGGER_GATEWAY_ENABLED=0
export REPLANNING_TRIGGER_POLICY_ENABLED=0
export AUTHORIZATION_POLICY_GATEWAY_ENABLED=0
export OPTIMIZATION_STRATEGY_MODE=AUTO
export LEGACY_CONVERGENCE_TARGET=LEGACY_DEFAULT
echo "[rollback-tier-c] env applied — restart backend required"
echo "  DECISION_RUNTIME_MODE=$DECISION_RUNTIME_MODE"
