#!/usr/bin/env bash
# Tier A — LEGACY_FALLBACK: keep CANONICAL runtime, optimization → legacy-frozen.
# See: src/decision-runtime/p4-phase/LEGACY_FALLBACK_RUNBOOK.md
set -euo pipefail
export DECISION_RUNTIME_MODE=CANONICAL
export OPTIMIZATION_STRATEGY_MODE=LEGACY
export CONSTRAINT_GATEWAY_MODE=ON
export CONSTRAINT_EVALUATION_GATEWAY_ENABLED=1
export CANONICAL_FULL_PLAN_SELECTION=1
export CANONICAL_EXECUTION_ENABLED=1
export AUTHORIZATION_POLICY_GATEWAY_ENABLED=1
export LEGACY_CONVERGENCE_TARGET=LEGACY_FALLBACK
echo "[rollback-tier-a] env applied — restart backend required"
echo "  DECISION_RUNTIME_MODE=$DECISION_RUNTIME_MODE"
echo "  OPTIMIZATION_STRATEGY_MODE=$OPTIMIZATION_STRATEGY_MODE"
