/**
 * P0 — Unified write-entry registry (As-Is + disposition).
 * SSOT for ops readouts and architecture lint. Evidence-based paths only.
 */

import type { WriteEntryRecord } from './write-entry-registry.types';

export const WRITE_ENTRY_REGISTRY: readonly WriteEntryRecord[] = [
  // ── Formal chain (KEEP) ───────────────────────────────────────────
  {
    id: 'rfc001.execute',
    objects: ['PlanVersion', 'ItineraryItem', 'TripDay', 'HotelAnchor', 'BookingStatus'],
    trigger: 'Route',
    surface: 'POST /api/rfc001/decisions/:id/execute',
    service: 'Rfc001PlanVersionApplyExecutor.execute',
    usesGuard: true,
    writesPlanVersion: true,
    writesLedger: true,
    owner: 'guardian-decision-core',
    disposition: 'FORMAL_CHAIN',
    notes: 'EffectivePlanWriteGuard + EffectivePlanWriter + EffectivePlanVersionStore',
  },
  {
    id: 'rfc001.rollback',
    objects: ['PlanVersion', 'ItineraryItem'],
    trigger: 'Route',
    surface: 'POST /api/rfc001/decisions/:id/rollback',
    service: 'Rfc001PlanVersionApplyExecutor.rollback',
    usesGuard: true,
    writesPlanVersion: true,
    writesLedger: true,
    owner: 'guardian-decision-core',
    disposition: 'FORMAL_CHAIN',
  },
  {
    id: 'decision-engine.execute',
    objects: ['PlanVersion', 'ItineraryItem'],
    trigger: 'Route',
    surface: 'POST /api/decision-engine/v1/trips/:tripId/decisions/:id/execute',
    service: 'DecisionEngineGateway → Rfc001PlanVersionApplyExecutor',
    usesGuard: true,
    writesPlanVersion: true,
    writesLedger: true,
    owner: 'guardian-decision-core',
    disposition: 'FORMAL_CHAIN',
  },
  {
    id: 'unified-decision.apply',
    objects: ['PlanVersion', 'ItineraryItem'],
    trigger: 'Route',
    surface: 'POST /api/trips/:tripId/decision-problems/:id/apply',
    service: 'UnifiedDecisionResolutionService',
    usesGuard: true,
    writesPlanVersion: true,
    writesLedger: true,
    owner: 'decision-runtime/gateway',
    disposition: 'FORMAL_CHAIN',
  },
  {
    id: 'arrange.proposal.apply',
    objects: ['ItineraryItem', 'HotelAnchor'],
    trigger: 'Route',
    surface: 'POST /api/trips/:tripId/arrange-itinerary/proposals/:id/apply',
    service: 'PlanProposalApplyService.apply',
    usesGuard: true,
    writesPlanVersion: false,
    writesLedger: false,
    owner: 'arrange-itinerary',
    disposition: 'FORMAL_CHAIN',
    notes: 'Must run under EffectivePlanWriter.runExecute',
  },
  {
    id: 'tep.local-repair.apply',
    objects: ['PlanVersion', 'ItineraryItem'],
    trigger: 'Route',
    surface: 'POST /api/mobile/.../tep-repairs/:id/accept',
    service: 'TepLocalRepairApplyService',
    usesGuard: true,
    writesPlanVersion: true,
    writesLedger: true,
    owner: 'tep',
    disposition: 'FORMAL_CHAIN',
  },
  {
    id: 'guide.canonical.accept',
    objects: ['Trip', 'TripDay', 'ItineraryItem', 'PlanVersion'],
    trigger: 'Route',
    surface: 'POST /api/guide-to-plan/sessions/:id/accept (canonical)',
    service: 'GuideCanonicalAcceptService.acceptAndExecute',
    usesGuard: true,
    writesPlanVersion: true,
    writesLedger: true,
    owner: 'guide-to-plan',
    disposition: 'FORMAL_CHAIN',
  },
  {
    id: 'iceland.initial-plan.apply',
    objects: ['Trip', 'TripDay', 'ItineraryItem', 'PlanVersion'],
    trigger: 'Route',
    surface:
      'POST /api/iceland-self-drive/trips/:tripId/initial-plan/proposals/:proposalId/apply',
    service: 'IcelandInitialPlanPrismaApplyService.materialize',
    usesGuard: true,
    writesPlanVersion: true,
    writesLedger: false,
    owner: 'iceland-self-drive',
    disposition: 'FORMAL_CHAIN',
    notes:
      'EffectivePlanWriter.runExecute; Iceland PlanVersion audit (not RFC-001 metadata PV); not OR-Tools',
  },

  // ── P0 high-risk bypasses (close / admin / proposal) ──────────────
  {
    id: 'attraction.auto-arrange.direct',
    objects: ['ItineraryItem'],
    trigger: 'Route',
    surface: 'POST /api/trips/:tripId/attraction-explore/auto-arrange (commitMode=direct)',
    service: 'AttractionExploreAutoArrangeService.autoArrange',
    usesGuard: false,
    writesPlanVersion: false,
    writesLedger: false,
    owner: 'attraction-explore',
    disposition: 'PROPOSAL_ONLY',
    notes: 'P0: direct mode blocked; use proposal → apply',
  },
  {
    id: 'contextual-recommendations.commit',
    objects: ['ItineraryItem', 'HotelAnchor'],
    trigger: 'Route',
    surface:
      'POST /api/trips/:tripId/contextual-recommendations/commit (+ mobile mirror)',
    service: 'ContextualRecommendationsCommitService.commit',
    usesGuard: false,
    writesPlanVersion: false,
    writesLedger: false,
    owner: 'contextual-recommendations',
    disposition: 'ADMIN_ONLY',
    notes: 'P0: C-end blocked when write chain on; admin bypass only',
  },
  {
    id: 'trips.schedule.put',
    objects: ['ItineraryItem', 'TripDay'],
    trigger: 'Route',
    surface: 'PUT /api/trips/:id/schedule',
    service: 'TripsService.saveSchedule → ScheduleConverterService',
    usesGuard: false,
    writesPlanVersion: false,
    writesLedger: false,
    owner: 'trips-core',
    disposition: 'ADMIN_ONLY',
  },
  {
    id: 'trips.items.batch-update',
    objects: ['ItineraryItem'],
    trigger: 'Route',
    surface: 'POST /api/trips/:id/items/batch-update',
    service: 'TripsController.batchUpdateItems (inline prisma)',
    usesGuard: false,
    writesPlanVersion: false,
    writesLedger: false,
    owner: 'trips-core',
    disposition: 'ADMIN_ONLY',
  },
  {
    id: 'trips.items.replace',
    objects: ['ItineraryItem'],
    trigger: 'Route',
    surface: 'POST /api/trips/:tripId/items/:itemId/replace',
    service: 'TripDraftService.replaceItem',
    usesGuard: false,
    writesPlanVersion: false,
    writesLedger: false,
    owner: 'trips-core',
    disposition: 'ADMIN_ONLY',
  },
  {
    id: 'trips.adjust',
    objects: ['TripDay', 'ItineraryItem'],
    trigger: 'Route',
    surface: 'POST /api/trips/:id/adjust',
    service: 'TripAdjustmentService.adjustTrip',
    usesGuard: false,
    writesPlanVersion: false,
    writesLedger: false,
    owner: 'trips-core',
    disposition: 'ADMIN_ONLY',
  },
  {
    id: 'readiness.apply-repair.deprecated',
    objects: ['ItineraryItem', 'TripDay'],
    trigger: 'Route',
    surface: 'POST /api/readiness/apply-repair',
    service: 'ReadinessController.applyRepair → ReadinessRepairService',
    usesGuard: true,
    writesPlanVersion: false,
    writesLedger: false,
    owner: 'readiness',
    disposition: 'ADMIN_ONLY',
    notes: 'Plan-class → feasibility apply-repair; prep-only ALLOW_METADATA',
  },
  {
    id: 'feasibility.apply-repair',
    objects: ['ItineraryItem', 'TripDay'],
    trigger: 'Route',
    surface: 'POST /api/trips/:tripId/feasibility-report/issues/:id/apply-repair',
    service: 'FeasibilityReportService.applyRepair',
    usesGuard: true,
    writesPlanVersion: false,
    writesLedger: false,
    owner: 'trip-constraint-solver',
    disposition: 'REQUIRE_GUARD',
  },
  {
    id: 'guide.legacy.accept',
    objects: ['Trip', 'TripDay', 'ItineraryItem'],
    trigger: 'Route',
    surface: 'POST /api/guide-to-plan/sessions/:id/accept (legacy materialize)',
    service: 'GuideTripMaterializerService.materialize',
    usesGuard: false,
    writesPlanVersion: false,
    writesLedger: false,
    owner: 'guide-to-plan',
    disposition: 'LEGACY_CLOSED',
    notes: 'P0: default closed; GUIDE_LEGACY_ACCEPT=1 + admin for escape',
  },

  // ── Trip shell create (allowed; not effective-plan mutation) ──────
  {
    id: 'trips.create',
    objects: ['Trip', 'TripDay'],
    trigger: 'Route',
    surface: 'POST /api/trips',
    service: 'TripsService.create',
    usesGuard: false,
    writesPlanVersion: false,
    writesLedger: false,
    owner: 'trips-core',
    disposition: 'ALLOW_METADATA',
    notes: 'Creates empty shell; itinerary still via formal chain',
  },
  {
    id: 'trips.update.status',
    objects: ['Trip', 'TripStatus'],
    trigger: 'Route',
    surface: 'PUT /api/trips/:id',
    service: 'TripsService.update',
    usesGuard: false,
    writesPlanVersion: false,
    writesLedger: false,
    owner: 'trips-core',
    disposition: 'ALLOW_METADATA',
  },
  {
    id: 'itinerary-items.booking-status',
    objects: ['BookingStatus', 'ItineraryItem'],
    trigger: 'Route',
    surface: 'PATCH /api/itinerary-items/:id (booking-status)',
    service: 'ItineraryItemsService.updateBookingStatus',
    usesGuard: false,
    writesPlanVersion: false,
    writesLedger: false,
    owner: 'itinerary-items',
    disposition: 'ADMIN_ONLY',
    notes: 'P0: booking status treated as plan-adjacent; admin or guard',
  },
  {
    id: 'itinerary-items.crud',
    objects: ['ItineraryItem', 'HotelAnchor'],
    trigger: 'Route',
    surface: 'POST|PATCH|DELETE /api/itinerary-items',
    service: 'ItineraryItemsService',
    usesGuard: false,
    writesPlanVersion: false,
    writesLedger: false,
    owner: 'itinerary-items',
    disposition: 'ADMIN_ONLY',
  },
  {
    id: 'iceland.preview.shell',
    objects: ['Trip'],
    trigger: 'Route',
    surface: 'POST /api/iceland-self-drive/trips',
    service: 'IcelandInitialPlanPreviewService.createTripShell',
    usesGuard: false,
    writesPlanVersion: false,
    writesLedger: false,
    owner: 'iceland-self-drive',
    disposition: 'ALLOW_METADATA',
    notes: 'In-memory shell until Apply; Apply creates Prisma Trip',
  },

  // ── Cron / internal (non-itinerary or already guarded) ────────────
  {
    id: 'cron.in-trip.environment-monitor',
    objects: ['Trip'],
    trigger: 'Cron',
    surface: 'EnvironmentMonitorJob */30',
    service: 'EnvironmentMonitorJob',
    usesGuard: false,
    writesPlanVersion: false,
    writesLedger: false,
    owner: 'in-trip-execution',
    disposition: 'ALLOW_METADATA',
    notes: 'Writes TripEnvironmentEvent / scores — not ItineraryItem',
  },
  {
    id: 'conflicts.resolve',
    objects: ['ItineraryItem'],
    trigger: 'Route',
    surface: 'POST /api/trips/:id/conflicts/resolve',
    service: 'TripConflictsService.resolveConflicts',
    usesGuard: true,
    writesPlanVersion: false,
    writesLedger: false,
    owner: 'trips-core',
    disposition: 'REQUIRE_GUARD',
  },
] as const;

export function getWriteEntryById(id: string): WriteEntryRecord | undefined {
  return WRITE_ENTRY_REGISTRY.find((e) => e.id === id);
}

export function listWriteEntriesByDisposition(
  disposition: WriteEntryRecord['disposition'],
): WriteEntryRecord[] {
  return WRITE_ENTRY_REGISTRY.filter((e) => e.disposition === disposition);
}

export function listWriteEntriesTouching(
  object: WriteEntryRecord['objects'][number],
): WriteEntryRecord[] {
  return WRITE_ENTRY_REGISTRY.filter((e) => e.objects.includes(object));
}
